language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - jruby-9.1.9.0
before_install:
  - gem install bundler
gemfile:
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
script:
  - bundle exec appraisal rake test
matrix:
  exclude:
    - rvm: jruby-19mode
      gemfile: gemfiles/rails50.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails51.gemfile
