language: ruby
cache: bundler
sudo: false
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - jruby
before_install:
  - gem install bundler
gemfile:
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
matrix:
  exclude:
    - rvm: 1.9
      gemfile: gemfiles/rails50.gemfile
    - rvm: 1.9
      gemfile: gemfiles/rails51.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails51.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails51.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails40.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails41.gemfile
